import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import Providers from "./provider";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className=" flex p-5 gap-7   bg-zinc-50 dark:bg-black">
           <div className="flex-4">
            سبد خرید
           </div>
          <Link href="/">صفحه اصلی</Link>
           <Link href="/login" >ثبت نام / ورود</Link>
         
        </div>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
